# Generated by Django 3.2 on 2023-02-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230205_2152'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique review1',
        ),
    ]
