# Generated by Django 3.2 on 2023-02-11 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Минимальное значение 0'), django.core.validators.MaxValueValidator(2023, 'Максимально значение текущий год')]),
        ),
    ]
