# Generated by Django 3.2 on 2023-02-05 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230205_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='titles',
        ),
    ]
