# Generated by Django 3.2 on 2023-02-11 17:23

import api.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[api.validation.validate_year]),
        ),
    ]
